### ISSUE TITLE
Integrate an in-app wallet feature with burner capability

### ISSUE THREAD

**Issue by Omeiza559** [FuelLabs/sway-farm#35]
The process of installing the existing wallet presents a suboptimal user experience. Implementing a burner wallet along with a faucet option would significantly enhance usability.
Thanks

**Comment by xgreenx** [comment]
Thank you for creating the issue. I will close it since it is not clear what the purpose is, and it looks like the desription is AI-generated. If it is not, you are welcome to reopen and add more description.
