### ISSUE TITLE
Update Wallet Recognition and Connectivity

### ISSUE THREAD

**Issue by bkr1956** [FuelLabs/sway-farm#42]
Hey everyone!

I've been working on addressing the issue where the game fails to recognize the wallet and establish a connection on the Fuel Chain network. After diving into the codebase, I've identified a few areas that need improvement.

Changes Made:

Updated wallet recognition logic to ensure compatibility with the latest wallet versions.
Implemented a more robust connection mechanism to establish a secure link with the Fuel Chain network.
Testing:
I've conducted thorough testing using different wallet versions and confirmed that the changes resolve the issue. The game now successfully identifies the wallet and establishes a connection with the Fuel Chain network without any hiccups.

things to fix 

Pull the latest changes from the repository.
Ensure you have the latest version of the supported wallet installed.
Launch the game and attempt to connect to the Fuel Chain network.
Best regard  
Bk

**Comment by K3lc3y** [comment]
If I make a new player using the same wallet I used before, will my coins come back?

**Comment by K3lc3y** [comment]
> thanks for the update and the work for me the wallet still not recognized, and the app offers to create new account only. What's more weird, is that on Fuel wallet all my eth is gone - showing zero. But for the same addy, on Fuelet the eth is still there.
> 
> so definitely something with the Fuel wallet i would say. I have updated the extension via chrome updater, no change.
> 
> Any tips pls?

I change to Fuelet, but my funds are gone
