### ISSUE TITLE
Proposal for Batch Confirmation Feature for Planted Seeds in Game Wallet

### ISSUE THREAD

**Issue by ashantilagos** [FuelLabs/sway-farm#45]
Currently, players of the blockchain game are required to individually confirm each seed planted in the game through their wallets. This process can be cumbersome and time-consuming, especially for players who plant multiple seeds.

Suggestion:
Introduce a batch confirmation feature that allows players to confirm all planted seeds in their wallet with a single action.

Technical Details:

Batch Confirmation Functionality: Implement a feature within the game's smart contract that allows players to confirm multiple seed plantings in a single transaction.

Transaction Aggregation: Develop a mechanism to aggregate the confirmation requests for all planted seeds into a single transaction, reducing blockchain congestion and gas fees.

User Interface Update: Update the game's user interface to include a "Batch Confirm" button in the wallet section, enabling players to trigger the confirmation process for all planted seeds.

Confirmation Status Tracking: Ensure that players can track the confirmation status of their planted seeds, providing transparency and accountability in the process.

Testing and Optimization: Thoroughly test the batch confirmation feature to ensure seamless integration with different wallets and optimal performance across various network conditions.

**Comment by Bamiboygraphics** [comment]
Kindly look into this please, This will ease the UX. I can plant select how many spots I want to plant and then confirm all in one txn
