### ISSUE TITLE
all my progress erased

### ISSUE THREAD

**Issue by Rallez73** [FuelLabs/sway-farm#52]
I did farm for weeks,

login today and all is on zero

**Comment by sarahschwartz** [comment]
Hi @Rallez73 , when was the last time you logged in? If it was more than a few weeks ago, the game has since been updated to a new testnet. If it was more recently, double check if you are on the right network, and if you are using the same account.

**Comment by Rallez73** [comment]
Hi,

last login it was february 16th.
