### ISSUE TITLE
Log events on actions

### ISSUE THREAD

**Issue by dmihal** [FuelLabs/sway-farm#63]
Every action should emit a log event, so the contracts can be indexed.

**Comment by moose-code** [comment]
Hi friends 💪  Following up on this, right now its possible to index data on Fuel fast using envio.

Here is a helpful example of whats being done with Thunder NFT marketplace: https://www.loom.com/share/36d53eae87344f3a835203f06ad708ac?sid=03f4a8d9-674b-4fe2-907c-9d6a5c0ee377

**Comment by moose-code** [comment]
P.s. I am having fun planting sttrawberries right now, looking forward to getting to the tomatos

**Comment by sarahschwartz** [comment]
The latest contract on testnet has logs now

**Comment by moose-code** [comment]
We have completed a tutorial for indexing Sway Farm 👍  https://docs.envio.dev/docs/tutorial-indexing-fuel

Think this can be very useful for showing global Sway Farm statistics and more on the user interface.
